# **Introduction**

In [ ]:
import torch

# CReating 1D singl element tensor.
x = torch.empty(1)
# Creating 1D 3 element tensor.
y = torch.empty(3)

print(x)
print(y)

tensor([3.4456e-28])
tensor([-7.0124e+35, -1.4080e+06, -4.2200e+27])


In [ ]:
# 2D tensor
x = torch.empty(2, 3)
print(x)

tensor([[ 9.8484e-07,  3.2668e-41, -4.5220e+32],
        [ 4.5482e-41,  8.9683e-44,  0.0000e+00]])


In [ ]:
# 1* 3D tensor with 3 rows and 3 columns.
tensor_3d = torch.empty(1,3,3)
print(tensor_3d)

tensor([[[9.8353e-07, 3.2668e-41, 9.8542e-07],
         [3.2668e-41, 0.0000e+00, 2.3334e+04],
         [0.0000e+00, 1.7130e-05, 0.0000e+00]]])


In [ ]:
# 2* 3D tensor with 3 rows and 3 columns.
tensor_3d = torch.empty(2,3,3)
print(tensor_3d)

tensor([[[ 9.8593e-07,  3.2668e-41,  9.8496e-07],
         [ 3.2668e-41,  4.4842e-44,  0.0000e+00],
         [ 1.5695e-43,  0.0000e+00, -3.5583e-36]],

        [[ 3.2673e-41,  9.8541e-07,  3.2668e-41],
         [ 1.4013e-44,  0.0000e+00,  9.8539e-07],
         [ 3.2668e-41,  1.5919e-42,  0.0000e+00]]])


In [ ]:
x = torch.rand(2, 2)
print(x)

tensor([[0.6067, 0.9362],
        [0.6523, 0.5174]])


In [ ]:
x = torch.rand(1, 4)
print(x)

tensor([[0.3078, 0.7399, 0.3103, 0.5403]])


In [ ]:
var = torch.ones(2, 2)
print(var)

tensor([[1., 1.],
        [1., 1.]])


In [ ]:
var = torch.zeros(2, 4, dtype = torch.int)
print(var)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)


In [ ]:
# Addition using third variable and function.
x = torch.rand(2,2)
y = torch.rand(2, 2)
z = torch.add(x,y)
print("The addition of x & y:", z)

# Inplace addition
y.add_(x)
print("The addition of x & y:", y)

The addition of x & y: tensor([[1.2564, 0.9706],
        [0.4036, 1.6390]])
The addition of x & y: tensor([[1.2564, 0.9706],
        [0.4036, 1.6390]])


In [ ]:
# Slicing operation
x = torch.rand(5, 3)
print("Whole x matrix:\n",x)
print("All rows and only 1 column:\n", x[:, 0])

Whole x matrix:
 tensor([[0.8444, 0.3249, 0.6216],
        [0.2891, 0.5697, 0.7922],
        [0.5393, 0.9506, 0.4208],
        [0.0761, 0.7673, 0.9265],
        [0.3456, 0.6413, 0.7467]])
All rows and only 1 column:
 tensor([0.8444, 0.2891, 0.5393, 0.0761, 0.3456])


# **Conversion:-**

In [ ]:
# To convert  "TENSOR" to numpy "ARRAY".
import torch
import numpy as np

a = torch.ones(5)
print(a)
print(type(a))

b = a.numpy()
print(b)
print(type(b))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>


# **Calculating Gradients.**

In [1]:
import torch

x = torch.randn(3, requires_grad = True)
y = x + 2
print("Forward pass Addition: ",y)

z = y*y*2
z = z.mean()         # NOTE: "z" has a scalar value.
print("Forward pass Multiplication: ",z)

# To calculate the gradient
z.backward()   # dz/dx
print(x.grad)

Forward pass Addition:  tensor([1.9115, 2.0761, 2.7711], grad_fn=<AddBackward0>)
Forward pass Multiplication:  tensor(10.4288, grad_fn=<MeanBackward0>)
tensor([2.5486, 2.7682, 3.6948])


In [ ]:
# When "z" does'nt has a scalar value.

x = torch.randn(3, requires_grad = True)
y = x+2

z = y*y*2
v = torch.tensor([0.1, 1.0, 0.001])
z.backward(v)
print(x.grad)

tensor([1.1444e+00, 9.1964e+00, 8.1262e-03])


# **Forgetting the gradients.**
There are three methods to forget the history or the "gradients":-


1.   ***Detach*** Fuction
2.   Setting "***requires_grad_***" to FALSE.
3.   Wrapping with "***WITH***" statement.

Here, we'll be discussing all the three methods.

In [ ]:
x = torch.randn(3, requires_grad = True)

In [ ]:
# To forget history "requires_grad_"
x.requires_grad_(False)
print(x)

tensor([ 1.4410, -1.1102, -0.5112])


In [ ]:
y = x.detach()
print(y)

tensor([ 1.4410, -1.1102, -0.5112])


In [ ]:
with torch.no_grad():
  y = x+2

  print(y)

tensor([3.4410, 0.8898, 1.4888])


In [8]:
# Dummy model

# Here, we create a weight tensor and print the gradient using backprop.
# But, it prints wrong gradients.
weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights*3).sum()

  # To calculate gradient.
  model_output.backward()

  print(weights.grad)


tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [7]:
# To resolve this issue, we need to reset the gradient to 0,
# so that it does'nt accumulates around epoches

weights = torch.ones(4, requires_grad=True)

for epoch in range(3):
  model_output = (weights*3).sum()

  # To calculate gradient.
  model_output.backward()

  print(weights.grad)

  weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


# **Backpropagation**